POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{"name":"login","email":"login@gmail.com","password":"1234567"}  

###

GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmM5MWRjOGFjMDdlYTA4ZTY3ZDdkZSIsImlhdCI6MTcyMzY0MzQyNH0.DYS3-xOfz0oPeI41JmreQ6mGQCXxWb46P3A2_SLKsYk


###
DELETE http://localhost:3000/users/66b9ae11e6dcaac9b419e5bd HTTP/1.1

###
PATCH http://localhost:3000/users/66b9e84e11006bc2188aaca8 HTTP/1.1
content-type: application/json

{"name": "yusuf besim1"}
###

PATCH http://localhost:3000/rooms/66c6e9d1a8ed614d80e09456 HTTP/1.1
content-type: application/json

{"name": "isim değişti"} 


# ----------

### task üzerinden task olusturma isteği atıyorum
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{"name":"besim odasına giriş tarzı", "description":"rap yapmak", 
"room": "66c6e4b4a8ed614d80e093d9","ownerId":"66c5c6f607b3399eec2bf80e"}


###taskların hepsini getir
GET http://localhost:3000/tasks HTTP/1.1

###Taskın detailini getir
GET http://localhost:3000/tasks/66b3270b7d4d129d0f84950e HTTP/1.1
###

###task delete
DELETE http://localhost:3000/tasks/66b9ffd053f9a5c62c517e5b HTTP/1.1



###Room
POST http://localhost:3000/rooms HTTP/1.1
content-type: application/json

{"name":"nazmiler Odası","ownerId":"66c5c6f607b3399eec2bf80e","color":"#9eeDDD"}

###rooms
GET http://localhost:3000/rooms HTTP/1.1

###room
GET http://localhost:3000/rooms/66b370a36f30023cdc9cd1f9 HTTP/1.1

###room delete
DELETE http://localhost:3000/rooms/66acd81396990c8b53d26b7e HTTP/1.1


###RoomAAAAA
POST http://localhost:3000/rooms/add-user HTTP/1.1
content-type: application/json

{"roomId":"66cdcf777e3c6bfe416c051d","userId":"66c5c6f607b3399eec2bf80e"}

###---------------------
###Room
POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{"name":"registerKayıt","email":"register@gmail.com","password":"1234567"}

###---------------------


###Room
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{"email":"register@gmail.com","password":"1234567"}

###---------------------
